### ISSUE TITLE
Automotive OBDII CAN ports are already terminated.

### ISSUE THREAD

**Issue by Mike4U** [teachop/FlexCAN_Library#11]
Guessing many may want to use this to look at their auto's OBD port.

The existing OBD CAN port under your car's dash is on a bus that is already terminated on both ends in order to run properly when nothing is plugged in.  Adding more termination resistors most likely will make matters worse when plugging into the port.

**Comment by Mike4U** [comment]
Forgot to add the above refers to the termination statement in the readme.

**Comment by teachop** [comment]
Yes, that is correct.  Termination resistors are located at both ends of the signal bus.

**Comment by Mike4U** [comment]
Newbie's don't know that.  Why don't you add it to the read me instead of:

 "Note that CAN will normally not work without termination resistors."

thanks

**Comment by teachop** [comment]
Ok.  I will get some explanation of the proper termination concept.


________________________________
