### ISSUE TITLE
mac osx interface

### ISSUE THREAD

**Issue by antimodular** [teachop/FlexCAN_Library#15]
hello again.

now that i got multiple teensy s running with your flexcan code i am thinking about how to get my computers host software to talk to the devices.

i guess the simplest would be to communicate over serial usb to the teensy and have the teensy then communicate with the can network.

but there are these usb-can devices out there like this one http://canusb.com.

what is your recommendation? do you know of a library that i could tap in to?

thanks again.

**Comment by pawelsky** [comment]
I believe the FlexCAN library thread on the PJRC forum will be much better place to ask this kind questions
https://forum.pjrc.com/threads/25101-CAN-Bus-Library-for-Teensy-3-1
